# Generated by Django 2.1.1 on 2018-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest1_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpartyparticipant',
            name='halarmarke',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='afterpartyparticipant',
            name='vip',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='halarmarke',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
